package com.example.ood_project.controllers;

import com.example.ood_project.models.Task;
import com.example.ood_project.repositories.TaskRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/tasks") // This means URL's start with /tasks (after Application path)
public class TaskController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private TaskRepository taskRepository;

    @PostMapping(path="") // Map ONLY POST Requests
    public @ResponseBody String addNewTask (@RequestBody Task task) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        taskRepository.save(task);
        return "Saved";
    }

    @GetMapping(path="")
    public @ResponseBody Iterable<Task> getAllTasks() {
        // This returns a JSON or XML with the tasks
        return taskRepository.findAll();
    }
}
